postman/urls.py
"""
If the default usage of the views suits you, simply use a line like
this one in your root URLconf to set up the default URLs::

    (r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),

Otherwise you may customize the behavior by passing extra parameters.

Recipients Max
--------------
Views supporting the parameter are: ``WriteView``, ``ReplyView``.
Example::
    ...View.as_view(max=3), name='write'),
See also the ``POSTMAN_DISALLOW_MULTIRECIPIENTS`` setting

User filter
-----------
Views supporting a user filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_user_filter(user):
        if user.get_profile().is_absent:
            return "is away"
        return None
    ...
    ...View.as_view(user_filter=my_user_filter), name='write'),

function interface:
In: a User instance
Out: None, False, '', 'a reason', or ValidationError

Exchange filter
---------------
Views supporting an exchange filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_exchange_filter(sender, recipient, recipients_list):
        if recipient.relationships.exists(sender, RelationshipStatus.objects.blocking()):
            return "has blacklisted you"
        return None
    ...
    ...View.as_view(exchange_filter=my_exchange_filter), name='write'),

function interface:
In:
    ``sender``: a User instance
    ``recipient``: a User instance
    ``recipients_list``: the full list of recipients or None
Out: None, False, '', 'a reason', or ValidationError

Auto-complete field
-------------------
Views supporting an auto-complete parameter are: ``WriteView``, ``ReplyView``.
Examples::
    ...View.as_view(autocomplete_channels=(None,'anonymous_ac')), name='write'),
    ...View.as_view(autocomplete_channels='write_ac'), name='write'),
    ...View.as_view(autocomplete_channel='reply_ac'), name='reply'),

Auto moderators
---------------
Views supporting an ``auto-moderators`` parameter are: ``WriteView``, ``ReplyView``.
Example::
    def mod1(message):
        # ...
        return None
    def mod2(message):
        # ...
        return None
    mod2.default_reason = 'mod2 default reason'
    ...
    ...View.as_view(auto_moderators=(mod1, mod2)), name='write'),
    ...View.as_view(auto_moderators=mod1), name='reply'),

function interface:
In: ``message``: a Message instance
Out: rating or (rating, "reason")
    with reting: None, 0 or False, 100 or True, 1..99

Others
------
Refer to documentation.
    ...View.as_view(form_classes=(MyCustomWriteForm, MyCustomAnonymousWriteForm)), name='write'),
    ...View.as_view(form_class=MyCustomFullReplyForm), name='reply'),
    ...View.as_view(form_class=MyCustomQuickReplyForm), name='view'),
    ...View.as_view(template_name='my_custom_view.html'), name='view'),
    ...View.as_view(success_url='postman:inbox'), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='view'),

"""
from __future__ import unicode_literals

try:
    from django.conf.urls import patterns, url  # django 1.4
except ImportError:
    from django.conf.urls.defaults import patterns, url  # django 1.3
from django.views.generic.base import RedirectView

from . import OPTIONS
from .views import (InboxView, SentView, ArchivesView, TrashView,
        WriteView, ReplyView, MessageView, ConversationView,
        ArchiveView, DeleteView, UndeleteView)


urlpatterns = patterns('',
    url(r'^inbox/(?:(?P<option>'+OPTIONS+')/)?$', InboxView.as_view(), name='inbox'),
    url(r'^sent/(?:(?P<option>'+OPTIONS+')/)?$', SentView.as_view(), name='sent'),
    url(r'^archives/(?:(?P<option>'+OPTIONS+')/)?$', ArchivesView.as_view(), name='archives'),
    url(r'^trash/(?:(?P<option>'+OPTIONS+')/)?$', TrashView.as_view(), name='trash'),
    url(r'^write/(?:(?P<recipients>[^/#]+)/)?$', WriteView.as_view(), name='write'),
    url(r'^reply/(?P<message_id>[\d]+)/$', ReplyView.as_view(), name='reply'),
    url(r'^view/(?P<message_id>[\d]+)/$', MessageView.as_view(), name='view'),
    url(r'^view/t/(?P<thread_id>[\d]+)/$', ConversationView.as_view(), name='view_conversation'),
    url(r'^archive/$', ArchiveView.as_view(), name='archive'),
    url(r'^delete/$', DeleteView.as_view(), name='delete'),
    url(r'^undelete/$', UndeleteView.as_view(), name='undelete'),
    (r'^$', RedirectView.as_view(url='inbox/', permanent=True)),
)

psicoya/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('accounts.urls')),
    url(r'^', include('searches.urls')),
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),
    url(r'^accounts/', include('userena.urls')),
]

searches/urls.py
from django.conf.urls import patterns, url
from .views import product_list, LandingPageView

urlpatterns = patterns('',
	url(r'^$', LandingPageView.as_view(), name="home"),
    url(r'^list$', product_list, name="list_filter")
)

searches/models.py
from django.db import models

accounts/forms.py
import random
from django import forms
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _
from userena.forms import SignupForm
from userena.utils import (signin_redirect, get_profile_model, get_user_model,
                           get_user_profile)
from userena.compat import sha_constructor
from django.forms import ModelForm
from .models import UserPsychologistProfile, Degrees, PaymentMethod, Treatment, Therapy, Specialty, PsychologistSpecialties, TreatmentsByPsychologist, PsychologistFocus, PsychologistPayment, PsychologistPromotion, PacientAge
from django.forms.widgets import CheckboxSelectMultiple, Select

class DegreesForm(ModelForm):
#    psychologist = forms.ChoiceField(widget=forms.HiddenInput(), label='')
    class Meta:
        model = Degrees
        fields = ["degree", "university", "year", "years_in_practice"]

class PsychologistSpecialtiesForm(ModelForm):
    class Meta:
        model = PsychologistSpecialties
        fields = ["top_specialty_one", "top_specialty_two", "top_specialty_three", "specialties"]

    def __init__(self, *args, **kwargs):
        super(PsychologistSpecialtiesForm, self).__init__(*args, **kwargs)
        self.fields["specialties"].widget = CheckboxSelectMultiple()
        self.fields["specialties"].queryset = Specialty.objects.all()

class TreatmentsByPsychologistForm(ModelForm):
    class Meta:
        model = TreatmentsByPsychologist
        fields = ["treatments", "therapies"]

    def __init__(self, *args, **kwargs):
        super(TreatmentsByPsychologistForm, self).__init__(*args, **kwargs)
        self.fields["treatments"].widget = CheckboxSelectMultiple()
        self.fields["treatments"].queryset = Treatment.objects.all()
        self.fields["therapies"].widget = CheckboxSelectMultiple()
        self.fields["therapies"].queryset = Therapy.objects.all()

class PsychologistFocusForm(ModelForm):
    class Meta:
        model = PsychologistFocus
        fields = ["pacient_ages", "spoken_languages", "work_on_weekends", "urgencies_service"]

    def __init__(self, *args, **kwargs):
        super(PsychologistFocusForm, self).__init__(*args, **kwargs)
        self.fields["pacient_ages"].widget = CheckboxSelectMultiple()
        self.fields["pacient_ages"].queryset = PacientAge.objects.all()

class PsychologistPaymentForm(ModelForm):
    class Meta:
        model = PsychologistPayment
        fields = ["min_price", "max_price", "free_consultation", "prepaid_medicine", "payment_methods"]

    def __init__(self, *args, **kwargs):
        super(PsychologistPaymentForm, self).__init__(*args, **kwargs)
        self.fields["payment_methods"].widget = CheckboxSelectMultiple()
        self.fields["payment_methods"].queryset = PaymentMethod.objects.all()

class PsychologistPromotionForm(ModelForm):
    class Meta:
        model = PsychologistPromotion
        fields = ["main_description", "second_description", "support_description"]

GENDER_CHOICES = (
	("male","Masculino"),
	("female","Femenino"),
	("other","Otro"),
)

class SignupFormExtra(SignupForm):
    name = forms.CharField(max_length=100, required=False)
    last_name = forms.CharField(max_length=100, required=False)
    gender = forms.ChoiceField(choices=GENDER_CHOICES)
    image = forms.ImageField(required=False)
    country = forms.CharField(max_length=100,required=False)
    state = forms.CharField(max_length=100,required=False)
    city = forms.CharField(max_length=100,required=False)
    address = forms.CharField(max_length=200,required=False)
    phone_number = forms.CharField(max_length=30,required=False)
    institution_name = forms.CharField(max_length=100,required=False)

    def __init__(self, *args, **kwargs):
        super(SignupFormExtra, self).__init__(*args, **kwargs)
        del self.fields['username']

    def save(self):
        """ Generate a random username before falling back to parent signup form """
        full_name = "{0} {1}".format(self.cleaned_data['name'], self.cleaned_data['last_name'])
        username = slugify(full_name)
        while True:
            try:
                user_exists = get_user_model().objects.get(username__iexact=username)
                if user_exists:
                    username = "{0}-{1}".format(username, sha_constructor(str(random.random()).encode('utf-8')).hexdigest()[:5])
            except get_user_model().DoesNotExist: break

        self.cleaned_data['username'] = username

        user = super(SignupFormExtra, self).save()

        user_profile = get_user_profile(user=user)

        user.first_name = self.cleaned_data['name']
        user.last_name = self.cleaned_data['last_name']
        user_profile.name = self.cleaned_data['name']
        user_profile.last_name = self.cleaned_data['last_name']
        user_profile.gender = self.cleaned_data['gender']
        user_profile.image = self.cleaned_data['image']
        user_profile.country = self.cleaned_data['country']
        user_profile.state = self.cleaned_data['state']
        user_profile.city = self.cleaned_data['city']
        user_profile.address = self.cleaned_data['address']
        user_profile.phone_number = self.cleaned_data['phone_number']
        user_profile.institution_name = self.cleaned_data['institution_name']

        user.save()
        user_profile.save()
        return user

searches/views.py
import django_filters
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.views.generic import TemplateView
from accounts.models import UserPsychologistProfile

class PsychologistFilter(django_filters.FilterSet):
    class Meta:
        model = UserPsychologistProfile
        fields = ['city']

def product_list(request):
    f = PsychologistFilter(request.GET, queryset=UserPsychologistProfile.objects.all())
    return render_to_response('searches/filter.html', {'filter': f}, context_instance=RequestContext(request))
    #if request.method == "POST":
    #    f = PsychologistFilter(request.POST, queryset=UserPsychologistProfile.objects.all())
    #    context = RequestContext(request)
    #    context["filter"] = f
    #    return render_to_json_response(context)
    #else:
    #    f = PsychologistFilter(request.POST, queryset=UserPsychologistProfile.objects.all())
    #    return render_to_response('searches/template.html', {'filter': f}, context_instance=RequestContext(request))

class LandingPageView(TemplateView):
	template_name = "searches/index.html"

templates/searches/index.html
{% load static from staticfiles %}
<!DOCTYPE html>
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

<!-- Basic Page Needs
================================================== -->
<meta charset="utf-8">
<title>Work Scout</title>

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- CSS
================================================== -->
<link rel="stylesheet" href="{% static "css/style.css" %}">
<link rel="stylesheet" href="{% static "css/colors/green.css" %}" id="colors">

<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

</head>

<body>
<div id="wrapper">


<!-- Header
================================================== -->
<header>
<div class="container">
	<div class="sixteen columns">
	
		<!-- Logo -->
		<div id="logo">
			<h1><a href="index.html"><img src="images/logo.png" alt="Work Scout" /></a></h1>
		</div>

		<!-- Menu -->
		<nav id="navigation" class="menu">
			<ul id="responsive">

				<li><a href="index.html" id="current">Home</a>
					<ul>
						<li><a href="index.html">Home #1</a></li>
						<li><a href="index-2.html">Home #2</a></li>
						<li><a href="index-3.html">Home #3</a></li>
						<li><a href="index-4.html">Home #4</a></li>
					</ul>
				</li>

				<li><a href="#">Pages</a>
					<ul>
						<li><a href="job-page.html">Job Page</a></li>
						<li><a href="job-page-alt.html">Job Page Alternative</a></li>
						<li><a href="resume-page.html">Resume Page</a></li>
						<li><a href="shortcodes.html">Shortcodes</a></li>
						<li><a href="pricing-tables.html">Pricing Tables</a></li>
						<li><a href="contact.html">Contact</a></li>
					</ul>
				</li>

				<li><a href="#">For Candidates</a>
					<ul>
						<li><a href="browse-jobs.html">Browse Jobs</a></li>
						<li><a href="browse-categories.html">Browse Categories</a></li>
						<li><a href="add-resume.html">Add Resume</a></li>
						<li><a href="manage-resumes.html">Manage Resumes</a></li>
						<li><a href="job-alerts.html">Job Alerts</a></li>
					</ul>
				</li>

				<li><a href="#">For Employers</a>
					<ul>
						<li><a href="add-job.html">Add Job</a></li>
						<li><a href="manage-jobs.html">Manage Jobs</a></li>
						<li><a href="manage-applications.html">Manage Applications</a></li>
						<li><a href="browse-resumes.html">Browse Resumes</a></li>
					</ul>
				</li>

				<li><a href="blog.html">Blog</a></li>
			</ul>


			<ul class="float-right">
				<li><a href="my-account.html#tab2"><i class="fa fa-user"></i> Registrate</a></li>
				<li><a href="my-account.html"><i class="fa fa-lock"></i> Inicia Sesión</a></li>
			</ul>

		</nav>

		<!-- Navigation -->
		<div id="mobile-navigation">
			<a href="#menu" class="menu-trigger"><i class="fa fa-reorder"></i> Menu</a>
		</div>

	</div>
</div>
</header>
<div class="clearfix"></div>


<!-- Banner
================================================== -->
<div id="banner" style="background: url(images/banner-home-01.jpg)">
	<div class="container">
		<div class="sixteen columns">
			
			<div class="search-container">

				<!-- Form -->
				<h2>Encuentra la mejor orientación psicológica en Colombia</h2>
				<form action="{% url "list_filter" %}" method="get">
				<input id="id_city" name="city" type="text" class="ico-02" placeholder="Ciudad. Ej: Bucaramanga" value=""/>
				<button type="submit"><i class="fa fa-search"></i></button>
				</form>

				<!-- Browse Jobs -->
				<div class="browse-jobs">
					Busca y contacta al mejor psicólogo para el tratamiento que necesitas</a>
				</div>
				
				<!-- Announce -->
				<!--<div class="announce">
					We’ve over <strong>15 000</strong> job offers for you!
				</div>-->

			</div>

		</div>
	</div>
</div>


<!-- Content
================================================== -->

<div class="container">
	
	<!-- Recent Jobs -->
	<div class="eleven columns">
	<div class="padding-right">
		<h3 class="margin-bottom-25">Últimas Preguntas</h3>
		<ul class="job-list">

			<li class="highlighted"><a href="job-page.html">
				<img src="images/job-list-logo-01.png" alt="">
				<div class="job-list-content">
					<h4>Marketing Coordinator - SEO / SEM Experience <span class="full-time">Full-Time</span></h4>
					<div class="job-icons">
						<span><i class="fa fa-briefcase"></i> King</span>
						<span><i class="fa fa-map-marker"></i> Sydney</span>
						<span><i class="fa fa-money"></i> $100 / hour</span>
					</div>
				</div>
				</a>
				<div class="clearfix"></div>
			</li>

			<li><a href="job-page.html">
				<img src="images/job-list-logo-02.png" alt="">
				<div class="job-list-content">
					<h4>Core PHP Developer for Site Maintenance <span class="part-time">Part-Time</span></h4>
					<div class="job-icons">
						<span><i class="fa fa-briefcase"></i> Cubico</span>
						<span><i class="fa fa-map-marker"></i> London</span>
						<span><i class="fa fa-money"></i> $50 / hour</span>
					</div>
				</div>
				</a>
				<div class="clearfix"></div>
			</li>

			<li><a href="job-page.html">
				<img src="images/job-list-logo-03.png" alt="">
				<div class="job-list-content">
					<h4>Restaurant Team Member - Crew <span class="full-time">Full-Time</span></h4>
					<div class="job-icons">
						<span><i class="fa fa-briefcase"></i> King</span>
						<span><i class="fa fa-map-marker"></i> Sydney</span>
						<span><i class="fa fa-money"></i> $15 / hour</span>
					</div>
				</div>
				</a>
				<div class="clearfix"></div>
			</li>

			<li><a href="job-page.html">
				<img src="images/job-list-logo-04.png" alt="">
				<div class="job-list-content">
					<h4>Power Systems User Experience Designer  <span class="internship">Internship</span></h4>
					<div class="job-icons">
						<span><i class="fa fa-briefcase"></i> Hexagon</span>
						<span><i class="fa fa-map-marker"></i> London</span>
						<span><i class="fa fa-money"></i> $75 / hour</span>
					</div>
				</div>
				</a>
				<div class="clearfix"></div>
			</li>

			<li><a href="job-page.html">
				<img src="images/job-list-logo-05.png" alt="">
				<div class="job-list-content">
					<h4>iPhone / Android Music App Development <span class="temporary">Temporary</span></h4>
					<div class="job-icons">
						<span><i class="fa fa-briefcase"></i> Mates</span>
						<span><i class="fa fa-map-marker"></i> New York</span>
						<span><i class="fa fa-money"></i> $115 / hour</span>
					</div>
				</div>
				</a>
				<div class="clearfix"></div>
			</li>
		</ul>

		<a href="browse-jobs.html" class="button centered"><i class="fa fa-plus-circle"></i> Show More Jobs</a>
		<div class="margin-bottom-55"></div>
	</div>
	</div>

	<!-- Job Spotlight -->
	<div class="five columns">
		<h3 class="margin-bottom-5">Nuestros mejores Psicólogos</h3>

		<!-- Navigation -->
		<div class="showbiz-navigation">
			<div id="showbiz_left_1" class="sb-navigation-left"><i class="fa fa-angle-left"></i></div>
			<div id="showbiz_right_1" class="sb-navigation-right"><i class="fa fa-angle-right"></i></div>
		</div>
		<div class="clearfix"></div>
		
		<!-- Showbiz Container -->
		<div id="job-spotlight" class="showbiz-container">
			<div class="showbiz" data-left="#showbiz_left_1" data-right="#showbiz_right_1" data-play="#showbiz_play_1" >
				<div class="overflowholder">

					<ul>

						<li>
							<div class="job-spotlight">
								<a href="#"><h4>Social Media: Advertising Coordinator <span class="part-time">Part-Time</span></h4></a>
								<span><i class="fa fa-briefcase"></i> Mates</span>
								<span><i class="fa fa-map-marker"></i> New York</span>
								<span><i class="fa fa-money"></i> $20 / hour</span>
								<p>As advertising & content coordinator, you will support our social media team in producing high quality social content for a range of media channels.</p>
								<a href="job-page.html" class="button">Apply For This Job</a>
							</div>
						</li>

						<li>
							<div class="job-spotlight">
								<a href="#"><h4>Prestashop / WooCommerce Product Listing <span class="freelance">Freelance</span></h4></a>
								<span><i class="fa fa-briefcase"></i> King</span>
								<span><i class="fa fa-map-marker"></i> London</span>
								<span><i class="fa fa-money"></i> $25 / hour</span>
								<p>Etiam suscipit tellus ante, sit amet hendrerit magna varius in. Pellentesque lorem quis enim venenatis pellentesque.</p>
								<a href="job-page.html" class="button">Apply For This Job</a>
							</div>
						</li>

						<li>
							<div class="job-spotlight">
								<a href="#"><h4>Logo Design <span class="freelance">Freelance</span></h4></a>
								<span><i class="fa fa-briefcase"></i> Hexagon</span>
								<span><i class="fa fa-map-marker"></i> Sydney</span>
								<span><i class="fa fa-money"></i> $10 / hour</span>
								<p>Proin ligula neque, pretium et ipsum eget, mattis commodo dolor. Etiam tincidunt libero quis commodo.</p>
								<a href="job-page.html" class="button">Apply For This Job</a>
							</div>
						</li>


					</ul>
					<div class="clearfix"></div>

				</div>
				<div class="clearfix"></div>
			</div>
		</div>

	</div>
</div>


<!-- Infobox -->
<div class="infobox">
	<div class="container">
		<div class="sixteen columns">Start Building Your Own Job Board Now</div>
		<div class="sixteen columns"><a href="my-account.html">Get Started</a></div>
	</div>
</div>


<!-- Footer
================================================== -->
<!--<div class="margin-top-15"></div>-->

<div id="footer">
	<!-- Main -->
	<div class="container">

		<div class="seven columns">
			<h4>About</h4>
			<p>Morbi convallis bibendum urna ut viverra. Maecenas quis consequat libero, a feugiat eros. Nunc ut lacinia tortor morbi ultricies laoreet ullamcorper phasellus semper.</p>
			<a href="#" class="button">Get Started</a>
		</div>

		<div class="three columns">
			<h4>Company</h4>
			<ul class="footer-links">
				<li><a href="#">About Us</a></li>
				<li><a href="#">Careers</a></li>
				<li><a href="#">Our Blog</a></li>
				<li><a href="#">Terms of Service</a></li>
				<li><a href="#">Privacy Policy</a></li>
				<li><a href="#">Hiring Hub</a></li>
			</ul>
		</div>
		
		<div class="three columns">
			<h4>Press</h4>
			<ul class="footer-links">
				<li><a href="#">In the News</a></li>
				<li><a href="#">Press Releases</a></li>
				<li><a href="#">Awards</a></li>
				<li><a href="#">Testimonials</a></li>
				<li><a href="#">Timeline</a></li>
			</ul>
		</div>		

		<div class="three columns">
			<h4>Browse</h4>
			<ul class="footer-links">
				<li><a href="#">Freelancers by Category</a></li>
				<li><a href="#">Freelancers in USA</a></li>
				<li><a href="#">Freelancers in UK</a></li>
				<li><a href="#">Freelancers in Canada</a></li>
				<li><a href="#">Freelancers in Australia</a></li>
				<li><a href="#">Find Jobs</a></li>

			</ul>
		</div>

	</div>

	<!-- Bottom -->
	<div class="container">
		<div class="footer-bottom">
			<div class="sixteen columns">
				<h4>Follow Us</h4>
				<ul class="social-icons">
					<li><a class="facebook" href="#"><i class="icon-facebook"></i></a></li>
					<li><a class="twitter" href="#"><i class="icon-twitter"></i></a></li>
					<li><a class="gplus" href="#"><i class="icon-gplus"></i></a></li>
					<li><a class="linkedin" href="#"><i class="icon-linkedin"></i></a></li>
				</ul>
				<div class="copyrights">©  Copyright 2015 by <a href="#">Work Scout</a>. All Rights Reserved.</div>
			</div>
		</div>
	</div>

</div>

<!-- Back To Top Button -->
<div id="backtotop"><a href="#"></a></div>

</div>
<!-- Wrapper / End -->


<!-- Scripts
================================================== -->
<script src="{% static "js/jquery-2.1.3.min.js" %}"></script>
<script src="{% static "js/custom.js" %}"></script>
<script src="{% static "js/jquery.superfish.js" %}"></script>
<script src="{% static "js/jquery.themepunch.tools.min.js" %}"></script>
<script src="{% static "js/jquery.themepunch.revolution.min.js" %}"></script>
<script src="{% static "js/jquery.themepunch.showbizpro.min.js" %}"></script>
<script src="{% static "js/jquery.flexslider-min.js" %}"></script>
<script src="{% static "js/chosen.jquery.min.js" %}"></script>
<script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
<script src="{% static "js/waypoints.min.js" %}"></script>
<script src="{% static "js/jquery.counterup.min.js" %}"></script>
<script src="{% static "js/jquery.jpanelmenu.js" %}"></script>
<script src="{% static "js/stacktable.js" %}"></script>



</body>
</html>

templates/searches/template.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="post">
    {% csrf_token %}
        {{ filter.form.as_p }}
        <input type="submit" />
    </form>
    {% for obj in filter %}
        {{ obj.name }} - {{ obj.city }}<br />
    {% endfor %}
{% endblock %}